version: '3.8'
services:
  app:
    container_name: pixabay-image-gallery
    build:
      context: .
      target: development
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
